---
title: "Lab 02 - Plastic waste"
author: "Cailey Fay "
date: "10.6.25"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read.csv("data/plastic-waste.csv")
```

## Exercises

### Exercise 1

Remove this text, and add your answer for Exercise 1 here.

```{r plastic-waste-continent}
ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.2)
df_filtered <-plastic_waste%>%
  filter(plastic_waste_per_cap < 3.5) 
ggplot(data = df_filtered, aes(x=plastic_waste_per_cap)) + geom_density()

ggplot(data=plastic_waste, mapping = aes(x=plastic_waste_per_cap, color = continent)) + geom_density()

ggplot(data=plastic_waste, mapping = aes(x=plastic_waste_per_cap, color = continent, fill = continent)) + geom_density()

ggplot(data=plastic_waste, mapping = aes(x=plastic_waste_per_cap, color = continent, fill = continent)) + geom_density(alpha=0.7)
```

### Exercise 2

```{r plastic-waste-density}
ggplot(data=plastic_waste, mapping = aes(x=plastic_waste_per_cap, color = continent, fill = continent)) + geom_density(alpha=.2)
#not sure why alpha is a characteristic of the plotting geom but color and fill are aesthetics. 
```

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.

```{r plastic-waste-violin}
ggplot(
  data = plastic_waste,
  mapping = aes(
    x = continent,
    y = plastic_waste_per_cap
  )
) +
  geom_boxplot()

geom_violin(
  mapping = NULL,
  data = NULL,
  stat = "ydensity",
  position = "dodge",
  trim = TRUE,
  bounds = c(-Inf, Inf),
  quantile.colour = NULL,
  quantile.color = NULL,
  quantile.linetype = 0L,
  quantile.linewidth = NULL,
  scale = "area",
  na.rm = FALSE,
  orientation = NA,
  show.legend = NA,
  inherit.aes = TRUE
)

stat_ydensity(
  mapping = NULL,
  data = NULL,
  geom = "violin",
  position = "dodge",
  orientation = NA,
  bw = "nrd0",
  adjust = 1,
  kernel = "gaussian",
  trim = TRUE,
  scale = "area",
  drop = TRUE,
  bounds = c(-Inf, Inf),
  quantiles = c(0.25, 0.5, 0.75),
  na.rm = FALSE,
  show.legend = NA,
  inherit.aes = TRUE
)

#confused by this 
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r plastic-waste-mismanaged}
ggplot(data=plastic_waste, mapping= aes(x=plastic_waste_per_cap, y=mismanaged_plastic_waste_per_cap) ) + geom_point()
```

```{r plastic-waste-mismanaged-continent}
ggplot(data=plastic_waste, mapping= aes(x=plastic_waste_per_cap, y=mismanaged_plastic_waste_per_cap, color=continent) ) + geom_point()
```

```{r plastic-waste-population-total}
ggplot(data=plastic_waste, mapping= aes(x=plastic_waste_per_cap, y=total_pop, color=continent) ) + geom_point()

ggplot(
  data = plastic_waste,
  mapping = aes(
    x = plastic_waste_per_cap,
    y = total_pop, color=continent
  )
) +
  geom_boxplot()
```

```{r plastic-waste-population-coastal}
plot()
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r recreate-viz}
CoastalProportion <- plastic_waste %>%
  mutate(CP = coastal_pop / total_pop)

ggplot(data = CoastalProportion, mapping = aes(x= CP, y=plastic_waste_per_cap, color=continent)) + geom_point() + geom_smooth() +
  labs(title= "Plastic Waste v Coastal Population Proportion",
       subtitle= "not quite right",
       x="Coastal Proportion",
       y= "Plastic Waste Per Capita")

```


